name: Flutter CI/CD Android & Web

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test & Build & Upload Artifact Android & Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: Nexus 6
          emulator-options: "-no-window -gpu swiftshader -no-snapshot -no-audio -no-boot-anim"
          emulator-boot-timeout: 600
          script: |
            for i in {1..5}; do
              adb devices
              adb shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done' && break
              echo "Retrying adb connection ($i)"
              sleep 15
            done
            flutter devices
            flutter test


      - name: Run Flutter Unit and Widget Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

      - name: Build WEB
        run: flutter build web --release

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: build/web/
