name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test & Build & Update Android & Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java environment
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter Unit and Widget Tests
        run: flutter test

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: flutter test integration_test

      - name: Build APK
        run: flutter build apk

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

      - name: Build WEB
        run: flutter build web --release

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: build/web/

  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter

      - name: Flutter Config
        run: ${{ github.workspace }}\_flutter\bin\flutter.bat config --enable-windows-desktop

      - name: Install Dependencies
        run: ${{ github.workspace }}\_flutter\bin\flutter.bat pub get

      - name: Build Windows Executable
        run: ${{ github.workspace }}\_flutter\bin\flutter.bat build windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-app
          path: build/windows/runner/Release/
